-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 22:00:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`HubProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HubProducts` (
  `ProductHaskKey` INT NOT NULL AUTO_INCREMENT,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `productCode` INT(20) NOT NULL,
  PRIMARY KEY (`ProductHaskKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SatProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SatProducts` (
  `ProductHaskKey` INT NOT NULL,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `nameOfProduct` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `quantityInStock` INT NOT NULL,
  INDEX `ProductHashKey_idx` (`ProductHaskKey` ASC) VISIBLE,
  CONSTRAINT `ProductHashKey`
    FOREIGN KEY (`ProductHaskKey`)
    REFERENCES `mydb`.`HubProducts` (`ProductHaskKey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Товары';


-- -----------------------------------------------------
-- Table `mydb`.`HubShop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HubShop` (
  `ShopHaskKey` INT NOT NULL AUTO_INCREMENT,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `shopNumber` INT(20) NOT NULL,
  PRIMARY KEY (`ShopHaskKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SatShops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SatShops` (
  `ShopHaskKey` INT NOT NULL,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `nameOfShop` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `building` VARCHAR(10) NOT NULL,
  INDEX `ShopHashKey_idx` (`ShopHaskKey` ASC) VISIBLE,
  CONSTRAINT `ShopHashKey`
    FOREIGN KEY (`ShopHaskKey`)
    REFERENCES `mydb`.`HubShop` (`ShopHaskKey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Киоски';


-- -----------------------------------------------------
-- Table `mydb`.`HubDeliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HubDeliveries` (
  `DeliveryHaskKey` INT NOT NULL AUTO_INCREMENT,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `deliveryNumber` INT(20) NOT NULL,
  PRIMARY KEY (`DeliveryHaskKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SatDeliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SatDeliveries` (
  `DeliveryHaskKey` INT NOT NULL,
  `dateOfDelivery` DATE NOT NULL,
  `quantityOfProduct` INT NOT NULL,
  INDEX `DeliveryHashKey_idx` (`DeliveryHaskKey` ASC) VISIBLE,
  CONSTRAINT `DeliveryHashKey`
    FOREIGN KEY (`DeliveryHaskKey`)
    REFERENCES `mydb`.`HubDeliveries` (`DeliveryHaskKey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Поставки: дата, киоск, поставщик, продукт, количество продукта';


-- -----------------------------------------------------
-- Table `mydb`.`HubSuppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HubSuppliers` (
  `SupplierHaskKey` INT NOT NULL AUTO_INCREMENT,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `supplierNumber` INT(20) NOT NULL,
  PRIMARY KEY (`SupplierHaskKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SatSuppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SatSuppliers` (
  `SupplierHaskKey` INT NOT NULL,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `contactEmail` VARCHAR(100) NOT NULL,
  INDEX `SupplierHashKey_idx` (`SupplierHaskKey` ASC) VISIBLE,
  CONSTRAINT `SupplierHashKey`
    FOREIGN KEY (`SupplierHaskKey`)
    REFERENCES `mydb`.`HubSuppliers` (`SupplierHaskKey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Поставщики';


-- -----------------------------------------------------
-- Table `mydb`.`LinkLineItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LinkLineItem` (
  `LinkLineItemHashKey` INT NOT NULL,
  `load` DATE NOT NULL,
  `record` TIMESTAMP(10) NOT NULL,
  `ShopHaskKey` INT NOT NULL,
  `DeliveryHaskKey` INT NOT NULL,
  `SupplierHaskKey` INT NOT NULL,
  `ProductHaskKey` INT NOT NULL,
  PRIMARY KEY (`LinkLineItemHashKey`),
  INDEX `ShopHashKey_idx` (`ShopHaskKey` ASC) VISIBLE,
  INDEX `DeliveryHashKey_idx` (`DeliveryHaskKey` ASC) VISIBLE,
  INDEX `SupplierHashKey_idx` (`SupplierHaskKey` ASC) VISIBLE,
  INDEX `ProductHashKey_idx` (`ProductHaskKey` ASC) VISIBLE,
  CONSTRAINT `ShopHashKey`
    FOREIGN KEY (`ShopHaskKey`)
    REFERENCES `mydb`.`HubShop` (`ShopHaskKey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DeliveryHashKey`
    FOREIGN KEY (`DeliveryHaskKey`)
    REFERENCES `mydb`.`HubDeliveries` (`DeliveryHaskKey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SupplierHashKey`
    FOREIGN KEY (`SupplierHaskKey`)
    REFERENCES `mydb`.`HubSuppliers` (`SupplierHaskKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductHashKey`
    FOREIGN KEY (`ProductHaskKey`)
    REFERENCES `mydb`.`HubProducts` (`ProductHaskKey`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
