-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 22:09:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deliveryNF3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deliveryNF3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deliveryNF3` DEFAULT CHARACTER SET utf8 ;
USE `deliveryNF3` ;

-- -----------------------------------------------------
-- Table `deliveryNF3`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryNF3`.`products` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `nameOfProduct` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `quantityInStock` INT NOT NULL,
  PRIMARY KEY (`idproduct`),
  UNIQUE INDEX `idproduct_UNIQUE` (`idproduct` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Товары';


-- -----------------------------------------------------
-- Table `deliveryNF3`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryNF3`.`shops` (
  `idshop` INT NOT NULL AUTO_INCREMENT,
  `nameOfShop` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `building` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idshop`),
  UNIQUE INDEX `idshop_UNIQUE` (`idshop` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Киоски';


-- -----------------------------------------------------
-- Table `deliveryNF3`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryNF3`.`suppliers` (
  `idsupplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `contactEmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsupplier`),
  UNIQUE INDEX `idsupplier_UNIQUE` (`idsupplier` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Поставщики';


-- -----------------------------------------------------
-- Table `deliveryNF3`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryNF3`.`deliveries` (
  `iddelivery` INT NOT NULL AUTO_INCREMENT,
  `dateOfDelivery` DATE NOT NULL,
  `idshop` INT NOT NULL,
  `idsupplier` INT NOT NULL,
  `idproduct` INT NOT NULL,
  `quantityOfProduct` INT NOT NULL,
  PRIMARY KEY (`iddelivery`),
  INDEX `idshop_idx` (`idshop` ASC) VISIBLE,
  INDEX `idsuppliers_idx` (`idsupplier` ASC) VISIBLE,
  INDEX `idproduct_idx` (`idproduct` ASC) VISIBLE,
  UNIQUE INDEX `iddelivery_UNIQUE` (`iddelivery` ASC) VISIBLE,
  CONSTRAINT `idshop`
    FOREIGN KEY (`idshop`)
    REFERENCES `deliveryNF3`.`shops` (`idshop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idsuppliers`
    FOREIGN KEY (`idsupplier`)
    REFERENCES `deliveryNF3`.`suppliers` (`idsupplier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idproduct`
    FOREIGN KEY (`idproduct`)
    REFERENCES `deliveryNF3`.`products` (`idproduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Поставки: дата, киоск, поставщик, продукт, количество продукта';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
